### ISSUE TITLE
No releases since 2009

### ISSUE THREAD

**Issue by webmaven** [brehaut/picoparse#4]
...yet obviously there has been activity in the repo as recently as May 2010.

BTW, I am listing this project here: https://github.com/webmaven/python-parsing-tools

**Comment by brehaut** [comment]
Thank you for pointing this out; I'll look at doing a release in the near future.

**Comment by brehaut** [comment]
I think its clear at this point that I'm not going to find time to make this release. In practice, I think this project is abandoned.
